config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get "/auth/facebook/callback" ,to: "sessions#create"
  get "/signout", to: "sessions#destroy"

  resources :gifts, only: [] do
    collection do
      get 'recommendation'
    end
  end

  resources :friends, only: [:new, :index]
  resources :funds, only: [:new, :create, :show] do
    resources :contributions, only: [:new, :create]
  end
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :user
  belongs_to :fund

  scope :approved, -> { where(approved: true) }

  def approve!
    update_attributes!(approved: true)
  end
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user , dependent: :destroy
  has_many :funds
  validates :uid , uniqueness: true

  def profile_image
    "http://graph.facebook.com/#{self.uid}/picture"
  end
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :user
  belongs_to :gift
  belongs_to :friend
  has_many :contributions

  def complete?
    remain_amount <= 0
  end

  def total_amount
    @total_amount ||= self.contributions.approved.pluck(:amount).reduce(0, :+)
  end

  def remain_amount
    @remain_amount ||= [0, self.gift.price - self.total_amount].max
  end

  def percentage
    total_amount.to_f / self.gift.price.to_f * 100
  end
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  has_many :funds

  enum gender: [:common, :male, :female]

  scope :for_user, ->(user) { for_age(user.age).for_gender(user.gender) }
  scope :for_age, ->(age) { where(arel_table[:min_age].lteq(age).and(arel_table[:max_age].gt(age))) }
  scope :for_gender, ->(gender) { where(arel_table[:gender].eq(self.genders[gender]).or(arel_table[:gender].eq(0))) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friends
  has_many :funds
  has_many :contributions

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.image = auth["info"]["image"]
      user.gender = auth["extra"]["raw_info"]["gender"]
      user.age = auth["extra"]["raw_info"]["age_range"]["min"]

      user.token = auth["credentials"]["token"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  before_action :require_login

protected
  def require_login
    origin = request.original_fullpath
    redirect_to root_path(origin: origin) unless current_user
  end

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
    @fund = Fund.find(params[:fund_id])
    @contribution_form = ContributionForm.new
  end

  def create
    @fund = Fund.find(params[:fund_id])
    @contribution_form = ContributionForm.new(contribution_form_params)

    if @contribution_form.save
      redirect_to fund_path(@fund)
    else
      render "new"
    end
  end

private
  def contribution_form_params
    params.require(:contribution_form).merge({
      user_id: current_user.id,
      fund_id: params[:fund_id]
    })
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @user = User.find(session[:user_id])
    @graph = Koala::Facebook::API.new(@user.token)

    @friends = @graph.get_connections("me", "friends")
  end

  def new
    @user = User.find(session[:user_id])
    @friend = @user.friends.new({uid: params[:uid], name: params[:name]})

    if @friend.save
      redirect_to recommendation_gifts_path(friend_id: @friend.uid)
    else
      redirect_to recommendation_gifts_path(friend_id: Friend.find_by_uid(params[:uid]))
    end
  end

end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  def new
    @gift = Gift.find(params[:gift_id])
    @friend = Friend.find(params[:friend_id])
    @fund_form = FundForm.new(params)

    render partial: "funds/new"
  end

  def create
    @fund_form = FundForm.new(fund_form_params)

    if @fund_form.save
      redirect_to fund_path(@fund_form.fund)
    else
      @gift = Gift.find(@fund_form.gift_id)
      @friend = Friend.find(@fund_form.friend_id)
      render new_fund_path
    end
  end

  def show
    @fund = Fund.find(params[:id])
  end

private
  def fund_form_params
    params.require(:fund_form).merge(user_id: current_user.id)
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def recommendation
    @friend = Friend.find(params[:friend_id])
    @user = User.find_by_id(@friend.user_id)
    @gifts = Gift.for_user(@user).page(params[:page]).per(8)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login

  def index
    redirect_to friends_path if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id

    redirect_to request.env['omniauth.origin'] || friends_path, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_path
    query = request.query_parameters.to_query
    "/auth/facebook?#{query}"
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/contributions/new.html.erb
<div class="cont-container container">
<h3 class="page-header">선물 참여하기<small> 최대 참여 가능 금액은 <%= number_to_won @fund.remain_amount %>입니다.</small></h3>
  <div class="row">
    <div class="cont-form-container col-md-8">
      <%= form_for @contribution_form, url: fund_contributions_path do |f| %>
        <div class="contribution-money form-group">
          <div class="input-money form-group">
              <%= button_tag "5,000원", type: "button", class: "btn btn-default ", data: { amount: 5000 } %>
              <%= button_tag "10,000원", type: "button", class: "btn btn-default ", data: { amount: 10000 } %>
              <%= button_tag "20,000원", type: "button", class: "btn btn-default ", data: { amount: 20000 } %>
              <div class="form-inline pull-right">
                <div class="input-group">
                  <%= f.label :amount, class: "sr-only" %>
                  <%= f.text_field :amount, class: "form-control ", type: "number", max: @fund.remain_amount, required: true %>
                  <div class="input-group-addon">원</div>
                </div>
              </div>
              <div class="clearfix"></div>
          </div>

          <div class="contacts">
            <div class="form-inline input-group">
              <%= f.text_field :payment, class: "form-control", id: "name", placeholder: "입금자명", required: true %>
              <%= f.text_field :contact, class: "form-control pull-right", id: "phone", placeholder: "연락 가능한 전화번호", required: true %>
            </div>
            <!-- <p>작성한 전화번호로 입금 및 배송 확인 문자가 전송됩니다</p> -->
          </div>
          <!-- <p class="pull-right">입금계좌 : 신한 110-383-537755 (김민혁)</p> -->
          <div class="clearfix"></div>
        </div>

        <div class="celebration-message">
          <h3 class=>축하 메시지</h3>
          <!-- <%= f.label :message, "축하 메시지" %> -->
          <%= f.text_area :message, class: "form-control", rows: 4, placeholder: "작성한 메시지는 롤링페이퍼 형태로 함께 전달됩니다" %>
        </div>

        <h3 class="page-header">결제 수단</h3>
          <p>현재는 무통장 입금만 가능합니다. 입금계좌 : 신한 110-383-537755 (김민혁)</p>

        <div class="submit-btn">
          <%= f.submit "참여하기", class: "btn btn-success btn-lg btn-block" %>
        </div>
      <% end %>

    </div>

    <div class="gift-container col-md-4">
      <!-- <h3 class="page-header">선물 소개</h3> -->

      <div class="text-center form-group">
        <%= image_tag @fund.gift.image, size: "304x304" %>
      </div>
      <h4 class="text-center"><%= @fund.gift.name %></h4>
    </div>
  </div>

</div>

app/views/friends/index.html.erb
<div class="container friends">
  <div class="header">
  </div>
  <h3 class="page-header">친구 찾기 <small class="pull-right"><%= text_field_tag 'query', nil, size: 40, placeholder: '이름 검색', id: "search", class: "form-control" %></small></h3>


  <div class="friends-grid">
    <div class="row">
      <div class="friend col-sm-4 col-md-2">
        <%= link_to new_friend_path(uid: @user.uid, name: @user.name) do %>
        <div class="thumbnail">
          <img src="http://graph.facebook.com/<%= @user.uid %>/picture?height=192&width=192">
          <div class="caption">
            <p>나에게 선물하기</p>
          </div>
        </div>
        <% end %>
      </div>

    <% (@friends*200).each do |f| %>
      <div class="friend col-sm-4 col-md-2">
        <%= link_to new_friend_path(uid: f['id'], name: f['name']) do %>
        <div class="thumbnail">
          <img src="http://graph.facebook.com/<%= f["id"] %>/picture?height=192&width=192">
          <div class="caption">
            <p><%= f["name"] %></p>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
    </div>

  </div>
</div>

app/views/funds/_new.html.erb
<div class="container">
  <%= form_for @fund_form, url: funds_path do |f| %>
    <%= f.hidden_field :friend_id %>
    <%= f.hidden_field :gift_id %>
    <div class="col-md-8 gift-description">
      <div class="gift-image" style="background-image: url(<%= @gift.image %>)"></div>
    </div>
    <div class="col-md-4">
      <div class="friend-information">
        <h4 class="gift-name"><%= @gift.name %></h4>
        <span class="gift-price pull-left"><%= number_to_won @gift.price %></span>
        <small class="pull-right">To <%= @friend.name %></small>
        <div class="clearfix"></div>
      </div>
      <div class="friend-information">
        <div class="form-group">
          <%= f.label :contact, "주최자 연락처" %>
          <%= f.text_field :contact, class: "form-control", placeholder: "전화번호나 이메일을 입력해주세요." %>
        </div>
        <div class="form-group">
          <%= f.label :situation, '상황' %>
          <%= f.select :situation, options_for_select(FundForm::SITUATIONS), {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description, '설명' %>
          <%= f.text_area :description, class: 'form-control', rows: 14, placeholder: "이 모금에 대한 설명을 작성해주세요." %>
        </div>
        <%= submit_tag "선물 시작하기", class: 'btn btn-lg btn-success btn-block'%>
      </div>
    </div>
  <% end %>
</div>

app/views/funds/new.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Macaron</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Action</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <%= form_for @fund_form, url: funds_path do |f| %>
    <%= f.hidden_field :friend_id %>
    <%= f.hidden_field :gift_id %>
    <div class="col-md-8 gift-description">
      <div class="gift-image" style="background-image: url(<%= @gift.image %>)"></div>
    </div>
    <div class="col-md-4">
      <div class="friend-information">
        <h4 class="gift-name"><%= @gift.name %></h4>
        <span class="gift-price pull-left"><%= number_to_currency @gift.price, unit: '₩', precision: 0 %></span>
        <small class="pull-right">To <%= @friend.name %></small>
        <div class="clearfix"></div>
      </div>
      <div class="friend-information">
        <div class="form-group">
          <%= f.label :contact, "주최자 연락처" %>
          <%= f.text_field :contact, class: "form-control", placeholder: "전화번호나 이메일을 입력해주세요." %>
        </div>
        <div class="form-group">
          <%= f.label :situation, '상황' %>
          <%= f.select :situation, options_for_select(FundForm::SITUATIONS), {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description, '설명' %>
          <%= f.text_area :description, class: 'form-control', rows: 14, placeholder: "이 모금에 대한 설명을 작성해주세요." %> 
        </div>
        <%= submit_tag "선물 시작하기", class: 'btn btn-lg btn-success btn-block'%>
      </div>
    </div>
  <% end %>
</div>

app/views/funds/show.html.erb
<% content_for :meta do %>
  <meta property="og:image" content="<%= @fund.friend.profile_image %>">
  <meta property="og:description" content="<%= @fund.description %>">
<% end %>
<div class="container fund-container">
    <div class="col-md-8 gift-description">
      <div class="gift-image" style="background-image: url(<%= @fund.gift.image %>)"></div>
      <div class="description">
        <article data-readmore="" aria-expanded="false" id="description" style="max-height: none; height:10px; word-break: break-all;">
          <%= simple_format @fund.description, class: "lead" %>
        </article>
        <a href="#" data-readmore-toggle aria-controls="description">더보기</a>
      </div>

      <h3 class="page-header">축하 메시지</h3>
      <% @fund.contributions.each_with_index do |contribution, index| %>
        <div class="media">
          <div class="media-left">
            <a href="#">
              <%= image_tag "http://graph.facebook.com/#{contribution.user.uid}/picture?height=64&width=64", size:"64x64" %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= contribution.user.name %></h4>
            <div class="contribution-message" data-readmore="" aria-expanded="false" id="message-<%= index %>" style="max-height: none; height: 10px; word-break: break-all;">
              <%= contribution.message %>
            </div>
            <a href="#" data-readmore-toggle aria-controls="message-<%= index %>">더보기</a>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="friend-information">
        <h3>받는 사람</h3>
        <%= image_tag @fund.friend.profile_image %>
        <%= @fund.friend.name %>
      </div>
      <div class="friend-information">
        <h4 class="gift-name"><%= @fund.gift.name %></h4>
        <span class="gift-price pull-left"><%= number_to_currency @fund.gift.price, unit: '₩', precision: 0 %></span>
        <div class="clearfix"></div>
      </div>
      <div class="friend-information">
        <div class="contribute-button">
          <% if @fund.complete? %>
            <%= link_to "모금 완료!", new_fund_contribution_path(@fund), class: 'btn btn-lg btn-success btn-block pull-right', disabled: true %>
          <% else %>
            <%= link_to "#{@fund.friend.name} 에게 선물하기", new_fund_contribution_path(@fund), class: 'btn btn-lg btn-success btn-block pull-right' %>
          <% end %>
        </div>
      </div>
      <div class="friend-information">
        <h3 class="page-header">모금 현황</h3>
        <h2 class="text-center contribute-amount"><%= number_to_currency @fund.total_amount, unit: '원', precision: 0, format: '%n%u' %></h2>

        <div class="progress">
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @fund.percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @fund.percentage %>%;">
            <%= number_with_precision(@fund.percentage, :precision => 0) %>%
          </div>
        </div>

        <h3 class="page-header">공유하기</h3>
        <%= render partial: 'share/link' %>

        <div class="contributors">
          <h3 class="page-header">참여자 <small>총 <%= @fund.contributions.size %>명</small></h3>
          <% @fund.contributions.each_slice(4) do |contributions| %>
            <div>
              <% contributions.each do |contribution| %>
                <div class="contributor-image pull-left">
                  <%= image_tag "http://graph.facebook.com/#{ contribution.user.uid}/picture?height=1000&width=1000" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
</div>

app/views/gifts/_gift.html.erb
<div class="col-md-3 gift-card col-xs-6" data-toggle="modal" data-target="#new-fund" data-gift-id="<%= gift.id %>" data-friend-id="<%= params[:friend_id] %>">
  <div class="recommendation-item">
    <div class="gift-image" style="background-image: url(<%= gift.image %>)"></div>
    <div class="gift-info">
      <div class="gift-name">
        <h4><%= gift.name %></h4>
      </div>
      <p class="gift-price">
        <%= number_to_currency gift.price, unit: '₩ ', precision: 0 %>
      </p>
    </div>
    <!-- <div class="gift-feeling">
      <div class="btn-group btn-group-justified" role="group" aria-label="Justified button group">
        <a href="#" class="btn btn-default" role="button" style="
      border-radius: 0;
  ">Good</a>
        <a href="#" class="btn btn-default" role="button">Bad</a>
        <a href="#" class="btn btn-default" role="button">Pick</a>
      </div>
    </div> -->
  </div>
</div>

app/views/gifts/new.html.erb
<script src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>
<body>
  <img id="kakao-login" src="<%= asset_path('kakao_story.png') %>"/>
  <div>
    <p id="post-result"></p>
  </div>

</body>

  <script>
    // 사용할 앱의 Javascript 키를 설정해 주세요.
    Kakao.init('83bcbdb62e754de52534c726ece4f0f7');

    $(document).ready( function(){

      $('#kakao-login').on('click', function(){
        Kakao.Auth.login({
          success: function() {
            Kakao.API.request( {
              url : '/v1/api/story/linkinfo',
              data : {
                url : "<%= @gift.link %>"
              }
            }).then(function(res) {
              return Kakao.API.request( {
                url : '/v1/api/story/post/link',
                data : {
                  link_info : res
                }
              });
            }).then(function(res) {
              return Kakao.API.request( {
                url : '/v1/api/story/mystory',
                data : { id : res.id }
              });
            }).then(function(res) {

              // Notify that link is Sucessfully shared. Kakao Story url is res.url

            }, function (err) {
              alert(JSON.stringify(err));
            });

          },

          fail: function(err) {
            alert(JSON.stringify(err))
          }
        });
      });
    } );

  </script>
</body>

<%= @gift.inspect %>
<%= render partial: "share/link" %>

app/views/gifts/recommendation.html.erb
<div class="recommendation-header">
  <span class="glyphicon glyphicon-gift" aria-hidden="true"></span>
  <h2>선물이 추천되었습니다!</h2>
  <p class="lead">마음에 드는 선물을 고르세요!</p>
</div>
<div class="container">
  <div class="row gifts" id="gifts-container">
    <%= render @gifts %>
  </div>
  <div class="row">
    <div class="recommendation-more col-md-4 col-md-offset-4">
      <button id="recommend" type="button" class="btn btn-default btn-block">계속 추천받기</button>
    </div>
  </div>
</div>

<div style="display: none">
<%= paginate @gifts %>
</div>

<div class="modal fade" id="new-fund" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog new-fund-modal">
    <div class="modal-content">
      <div class="modal-body" id="new-fund-body">

      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id='cover'></div>
<div class="intro">
  <div class="content">

    <div id="user_nav">
      <div class="main_text">
      <h1> Macaron </h1>
        <p class="lead">친구들과 함께 특별한 선물을 준비해보세요</p>
      </div>

      <div>
      <%= link_to login_path, id:"fb-link" do %>
        <div class="fb-join">
          <div class="fb-join-image"><img src="https://d12hfz37g51hrt.cloudfront.net/assets/intro/intro_btn_fb-86680a3702eb0c41f5cf6412554e2360.png"></div>
          <div class="fb-join-text">페이스북으로 시작하기</div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Macaron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="title" content="Macaron Gift">
  <meta name="description" content="선물 모금에 참여해요!">
  <meta name="keywords" content="선물, 생일, 친구">
  <meta property="og:site_name" content="Macaron Gift">
  <meta property="og:url" content="<%= request.original_url %>">
  <meta property="og:type" content="article">
  <%= yield :meta %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Macaron", friends_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "로그아웃", signout_path %></li>
    </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/layouts/home_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Macaron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/share/_link.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "http://connect.facebook.net/ko_KR/sdk.js#xfbml=1&appId=1562660880653325&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>
  window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>

<div class="share-container">
  <div>
    <div style="border:none;">
      <div>
        <div class="input-group">
          <input type="text" class="form-control" value="<%= Googl.shorten(request.original_url, nil, "AIzaSyD2MQg2ZcgjFOtI-aTDktHKR6dm5K76A6Q").short_url %>" disabled>

          <div class="input-group-btn">
            <button type="button" id="share-btn" data-clipboard-text="<%= Googl.shorten(request.original_url, nil, "AIzaSyD2MQg2ZcgjFOtI-aTDktHKR6dm5K76A6Q").short_url %>" class="btn btn-default" title="Copy to Clipboard" data-toggle="tooltip" data-placement="top"><span class="glyphicon glyphicon-link"></span></button>
          </div>
        </div>
        <br/>
        <a class="sns-button" href="http://www.facebook.com/share.php?u=<%= request.original_url %>" onclick="return fbs_click()" target="_blank"><%= image_tag "fb-square.png", size: "40x40" %></a>
        <a class="sns-button" href="https://twitter.com/share?hashtags=Macaron,선물&text=OOO님을 위해 함께 선물을 준비해요!"><%= image_tag "twitter-square.png", size: "40x40" %></a>
      </div>
    </div>
  </div>

  <script>
    $(document).ready(function(){
      var client = new ZeroClipboard( $("#share-btn") );
      $('#share-btn').on('click', function(){
        $(this).attr( "data-original-title", "Copied!" );
        $(this).tooltip('show');
      });
      $('#share-btn').mouseover( function(){
        $(this).tooltip('show');
      });
      $('#share-btn').mouseout( function(){
        $(this).attr( "data-original-title", "Copy to Clipboard" );
      });
    });
  </script>

</div>